version: "3"
services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysqlservice-container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE : userdb
    networks:
      - springcloud-lendingLane-net

  mongodb:
    image: mongo:latest
    container_name: mongodb-container

    ports:
      - "27017:27017"
    networks:
      - springcloud-lendingLane-net

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/neo4j123


    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - springcloud-lendingLane-net


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: always

    networks:
      - springcloud-lendingLane-net





  eureka-server:
    build: eureka-server/
    container_name: eureka-server-service
    networks:
      - springcloud-lendingLane-net
    restart: always
    ports:
      - "8761:8761"

  api-gateway:
    build: api-gateway/
    container_name: api-gateway-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - springcloud-lendingLane-net

    ports:
      - "9002:9002"




  authentication:
    build: authentication/
    container_name: authentication-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - eureka-server
      - api-gateway
      - rabbitmq

    restart: always

    networks:
      - springcloud-lendingLane-net

    ports:
      - "8080:8080"



  borrower:
    build: borrower/
    container_name: borrower-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
      - rabbitmq

    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8083:8083"

  lender:
    build: lender/
    container_name: lender-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq

    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
      - rabbitmq

    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8082:8082"

  chat:
    build: chat/
    container_name: chat-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
      - rabbitmq

    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8085:8085"



  recommendation:
    build: recommendation/
    container_name: recommendation-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq




    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
      - rabbitmq
      - neo4j

    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8087:8087"


  review:
    build: review/
    container_name: review-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8086:8086"

  loan:
    build: loan/
    container_name: loan-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq


    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
      - rabbitmq

    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8084:8084"

  payment:
    build: payment/
    container_name: payment-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq

    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
      - rabbitmq

    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8081:8081"

#  contact-us:
#    build: contactus/
#    container_name: contactus-service
#    environment:
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
#
#    depends_on:
#      - mongodb
#      - eureka-server
#      - api-gateway
#    restart: always
#    networks:
#      - springcloud-lendingLane-net
#
#    ports:
#      - "8089:8089"



  notifications:
    build: notifications/
    container_name: notifications-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq

    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
      - rabbitmq

    restart: always
    networks:
      - springcloud-lendingLane-net

    ports:
      - "8092:8092"



#  product-webapp:
#    build: product-webapp/
#    image: product-webapp
#    depends_on:
#      - eureka-server
#      - api-gateway
#    restart: always
#    container_name: product-webapp
#    environment:
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
#
#    ports:
#      - "8099:8099"



  angular:
    build: product-webapp/lendinglane
    container_name: angular


    ports:
      - "4200:80"

    networks:
      - springcloud-lendingLane-net




networks:
  springcloud-lendingLane-net:
    driver: bridge


