eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/api/v1/authentication/**
          filters:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}


        - id: borrower
          uri: lb://borrower
          predicates:
            - Path=/api/v1/borrower/**
          filters:
            - RewritePath=/borrower(?<segment>/?.*), $\{segment}


        - id: chat
          uri: lb://chat
          predicates:
            - Path=/api/v1/chat/**
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}


        - id: contactus
          uri: lb://contactus
          predicates:
            - Path=/api/v1/contactus/**
          filters:
            - RewritePath=/contactus(?<segment>/?.*), $\{segment}

        - id: lender
          uri: lb://lender
          predicates:
            - Path=/api/v1/lender/**
          filters:
            - RewritePath=/lender(?<segment>/?.*), $\{segment}

        - id: product-webapp
          uri: lb://product-webapp
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}


        - id: loan
          uri: lb://loan
          predicates:
            - Path=/api/v1/loan/**
          filters:
            - RewritePath=/loan(?<segment>/?.*), $\{segment}

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - RewritePath=/notification(?<segment>/?.*), $\{segment}

        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - RewritePath=/payment(?<segment>/?.*), $\{segment}

        - id: recommendation
          uri: lb://recommendation
          predicates:
            - Path=/api/v1/recommendation/**
          filters:
            - RewritePath=/recommendation(?<segment>/?.*), $\{segment}

        - id: review
          uri: lb://review
          predicates:
            - Path=/api/v1/review/**
          filters:
            - RewritePath=/review(?<segment>/?.*), $\{segment}




