#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true

server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authentication
          uri: http://localhost:8088/
          predicates:
            - Path=/api/v1/authentication/**

        - id: borrower
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/borrower/**


        - id: chat
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/chat/**


        - id: contactus
          uri: http://localhost:8089/
          predicates:
            - Path=/api/v1/contactus/**

        - id: lender
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/lender/**

        - id: product-webapp
          uri: http://localhost:4200/
          predicates:
            - Path=/**

        - id: loan
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1/loan/**

        - id: notification
          uri: http://localhost:8092/
          predicates:
            - Path=/api/v1/notification/**

        - id: payment
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/payment/**

        - id: recommendation
          uri: http://localhost:8087/
          predicates:
            - Path=/api/v1/recommendation/**

        - id: review
          uri: http://localhost:8086/
          predicates:
            - Path=/api/v1/review/**